name: Wind Field Visualize

on:
  # 手动触发
  workflow_dispatch:
  
  # 推送到 main 分支时触发（可选）
  push:
    branches:
      - main
    paths:
      - 'main.py'
      - 'requirements.txt'
      - '.github/workflows/**'

jobs:
  run-visualization:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libeccodes-dev libgeos-dev libproj-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Create .cdsapirc configuration
      run: |
        mkdir -p $HOME
        echo "url: https://cds.climate.copernicus.eu/api" > $HOME/.cdsapirc
        echo "key: ${{ secrets.CDS_API_KEY }}" >> $HOME/.cdsapirc
      env:
        CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
    
    - name: Run wind field visualization
      run: |
        python main.py
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: wind-field-data-${{ github.run_number }}
        path: khanun_data/
        retention-days: 30
    
    - name: Commit and push results (optional)
      if: success()
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add khanun_data/
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update: Wind field data $(date +'%Y-%m-%d %H:%M:%S')" && git push)
      continue-on-error: true
